experiment:
  mode: sandbox
  name: navigation
  version: v1
  batch: b1
  conditions: ["nav"]

HIT:
  lifetime: 3
  duration: 4.0
  base_pay: 4.00
  max_bonus: 12.00
  keywords: []
  frame_height: 800
  url: https://andersonlab.net/sfnavigation/sf.html
  title: Space Fortress Study
  description: |
    This task is part of a research study conducted by Dr. John R. Anderson at Carnegie Mellon University.
    In this HIT you will pilot a spaceship in a two dimensional, frictionless space. The goal is to maximize your points by destroying the fortress and avoiding danger.
    The expected duration is about an hour.
    You will earn up to <<maxbonus>> in bonus money depending on how well you play the game.
